project:
  type: website
  output-dir: docs

website:
  title: "Shubhanga Satyal-MUSA 5080 Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: labs
        menu: 
          - href: labs/lab0/lab0_template.qmd
            text: "lab 0: dplyr Basic"

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true

execute:
  freeze: auto
